apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvctest
  namespace: stage-nginx-namespace
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
